### PR TITLE
Upgrade deps and improve outside contributor support

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Some prep work for an upcoming PR.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@rubensousa any updates?

**Comment by rubensousa** [comment]
Merged, thank you!

**Comment by SUPERCILEX** [comment]
Awesome sauce! 😀 Do you know when we can expect a minor release?

**Comment by rubensousa** [comment]
I've released 1.4 now.

**Comment by SUPERCILEX** [comment]
Sweet, thanks! 😀🚀

**Pull request merged**
